#!/usr/bin/with-contenv bash

echo "**** installing nix ****"

# Determine if setup is needed
if [ ! -f /nix ] 
then
  echo "Nix not installed, installing it now"
  mkdir /nix
  chown -R abc /nix
  mkdir -p /etc/nix

  echo "sandbox = false" >> /etc/nix/nix.conf
  echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  echo "substituters = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/" >> /etc/nix/nix.conf
  echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" >> /etc/nix/nix.conf

  apt-get install --no-install-recommends -y curl xz-utils
  curl -L https://nixos.org/nix/install > install.sh
  chmod +x install.sh
  s6-setuidgid abc sh ./install.sh --no-daemon
  rm install.sh

  echo 'export PATH=$PATH:/config/.nix-profile/bin' >> /config/.bashrc
else
  echo "Nix already installed"
fi