#!/usr/bin/with-contenv bash

echo "**** installing rust dev environment using abc ****"

# Determine if setup is needed
if [ ! -f /config/.cargo ] 
then
  echo "Rust not installed, installing it now"
  apt-get install --no-install-recommends -y curl gcc
  s6-setuidgid -u abc -g abc curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | s6-setuidgid abc sh -s -- -y
else
  echo "Rust already installed"
fi